CPF_work_schedule-master/config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/login')
  resources :users do
    resources :schedule_actual_times
  end
  get '/main_page', to: 'dashboard#index'
  get '/login', to: 'login#login_new'
  post '/login',to: 'login#create'
  get '/register', to: 'login#register_new'
  post '/register',to: 'login#register'
  get '/register_user', to: 'dashboard#register_user'
  post '/register_user',to: 'dashboard#register'
  get '/logout',to: 'dashboard#destroy'
  get '/timestamp/:id',to: 'dashboard#check_timestamp',as: 'timestamp'
  get '/manage_user',to: 'manage_user#index'
  post '/manage_user',to: 'manage_user#manage_worker'
  post '/manage_user/update_ot',to: 'manage_user#update_ot'
  get '/num_user',to: 'dashboard#get_num_person_shiftcode'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

CPF_work_schedule-master/app/controllers/manage_user_controller.rb
class ManageUserController < ApplicationController
    def index
        @current_user = current_user
        @actual_time = ScheduleActualTime.all
    end
    def manage_worker
        if params[:commit] == "ยืนยัน"
            unless params["ot_time_select"].nil?
                self.set_plan(params["ot_time_select"])
            end
            unless params['department_select'].nil?
                self.set_department(params['department_select'])
            end
        else
            self.update_ot
        end
        redirect_to manage_user_path
    end
    def set_plan(plan_all)
        plan_all.each do |item|
            item = create_array_from_object(item)
            @ot_time = item[0]
            @id_user = item[1]
            user = User.find(@id_user)
            
            shifttime = user.shiftcodes.first
            @ot_time = Time.parse(@ot_time)
            new_shift_time = DateTime.now().change(hour:shifttime.start_in.hour,min:shifttime.start_in.min)
            if  DateTime.now() < new_shift_time#plan ก่อนเวลาเข้างาน
                @new_plan_time = SchedulePlantime.create(shift_code:shifttime.code_name,time_in:new_shift_time,time_out:new_shift_time+9.hours,ot_time:@ot_time,factory_name:user.factory,department_name:user.department)
            else#plan หลังเข้างาน
                @new_plan_time = SchedulePlantime.create(shift_code:shifttime.code_name,time_in:new_shift_time+1.days,time_out:new_shift_time+1.days+9.hours,ot_time:@ot_time,factory_name:user.factory,department_name:user.department)
            end
            user.schedule_plantimes << @new_plan_time
        end
    end

    def set_department(department_all)
        department_all.each do |department_each|
            department_each = create_array_from_object(department_each)
            @department_plan = department_each[0].delete('\\"')
            @id_user_d = department_each[1]
            @user = User.find(@id_user_d)
            unless (@user.department == @department_plan) || @department_plan.nil?
                User.find(@id_user_d).update(department: @department_plan)
                User.find(@id_user_d).schedule_actual_times.last.update(department_name:@department_plan)
                User.find(@id_user_d).histories.last.update(department_name:@department_plan)
            end
        end
    end

    def create_array_from_object(array_string)
        item = array_string.split(",")
        for value in item do
            if value.include? "["
                some_item = value[1..value.length-1]
            elsif value.include? "]"
                @id_user = value[0..value.length-2]
            end
        end
        return [some_item,@id_user]
    end
    def update_ot
        @ot_who_update = params["ot_time_select"]
        unless @ot_who_update.nil?
            @ot_who_update.each do |item|
                item = create_array_from_object(item)
                @ot_time = item[0]
                @id_user = item[1]
                @ot_time = Time.parse(@ot_time)
                user = User.find(@id_user)
                if user.schedule_plantimes.length > 0
                    user.schedule_plantimes.last.update(ot_time:@ot_time)
                end
            end
        end
        redirect_to manage_user_path 
    end
end

CPF_work_schedule-master/app/helpers/manage_user_helper.rb
module ManageUserHelper
end

CPF_work_schedule-master/app/views/manage_user/_manage_plan_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@100;300&display=swap" rel="stylesheet">

    <script type="text/javascript">  
            function selects(){  
                var ele=document.getElementsByName('chk');  
                for(var i=0; i<ele.length; i++){  
                    if(ele[i].type=='checkbox')  
                        ele[i].checked=true;  
                }  
            }  
            function deSelect(){  
                var ele=document.getElementsByName('chk');  
                for(var i=0; i<ele.length; i++){  
                    if(ele[i].type=='checkbox')  
                        ele[i].checked=false;   
                }  
            }             
        </script>  
</head>

<body>
    <script>
    </script>
    <table>
        <tbody>
            <td class="block">
            <label>
                <input type="checkbox" data-checkbox-select-all-target="checkboxAll" />
                <span>เลือกทั้งหมด / ไม่เลือก</span>
            </label>
            </td>

            <td class="block">
            <label>
                <input type="checkbox" data-checkbox-select-all-target="checkbox" value="1" />
                <span>Team 1</span>
            </label>
            </td>

            <td class="block">
            <label>
                <input type="checkbox" data-checkbox-select-all-target="checkbox" checked="checked" value="2" />
                <span>Team 2</span>
            </label>
            </td>

            <td class="block">
            <label>
                <input type="checkbox" data-checkbox-select-all-target="checkbox" value="3" />
                <span>Team 3</span>
            </label>
            </td>
        </tbody>
        </table>
    <%=form_tag do%>
        <div class="form-check">
            <input type="button" onclick='deSelect()' value="Deselect"/> 
            <%all_time = []%>
            <% for hour in (0..4)%>
                <%for min in (0..1)%>
                    <% all_time.push((hour.to_s+":"+(min*30).to_s))%>
                <%end%>
            <%end%>
            <%all_department = ['งานถอนขน','งานไก่ตกราว','งานเชือดไก่','งานจัดเก็บและจ่ายสินค้าแช่แข็ง']%>
            <%=select_tag(:ot_time,options_for_select(all_time))%>
        </div>

        <table class="table table-striped table-light" border="1" width="50%" cellspacing='0' cellpadding='10'>
            <thead>
                <th>ชื่อ-นามสกุล</th>
                <th>เวลา-เข้า</th>
                <th>เวลา-ออก</th>
                <!--<th>โรงงาน</th>-->
                <th>OT check</th>
                <th>OT time</th>
                <th>แผนก</th>
            </thead>
            <tbody id="time_object">
                <% @actual_time.each do |row|%>
                    <tr id=<%= User.find(row.user_id).name%>>
                        <% unless User.where(id:row.user_id,role:'คนงานทั่วไป',department: "งานถอนขน").length == 0%>
                            <td><%= User.find(row.user_id).name%></td>
                            <td><%= row.time_in.strftime("%H:%M:%S")%></td>
                            <% if row.time_out.nil?%>
                                <td>#</td>
                            <% else %>
                                <td><%= row.time_out.strftime("%H:%M:%S")%></td>
                            <% end %>
                            <!--<td><%= User.find(row.user_id).factory%></td>-->
                            <td><input type="checkbox" name="chk" value= <%row.user_id%> ></td>
                            <%# <td><%=check_box_tag(":ot_time_#{row.user_id}".to_sym)%>
                            <td><%=select_tag("ot_time_#{row.user_id}".to_sym,options_for_select(all_time))%></td>
                            <td><%=select_tag("department_#{row.user_id}".to_sym,options_for_select(all_department))%></td>
                        <%end%>      
                    </tr>
                <%end%>                       
            </tbody>
        </table>
        <%=link_to "ยกเลิก",main_page_path,class:"btn btn-danger"%>
        <%=submit_tag("ยืนยัน",class:"btn btn-success")%>
    <%end%>
</body>
</html>

CPF_work_schedule-master/app/views/manage_user/_manage_plan_w1_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">  
    <link href="app/assets/stylesheet/style.css.scss" rel="stylesheet">
    <!-- font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@100;300&display=swap" rel="stylesheet">
</head>

<body>
    <div class="tab">
        <button class="tablinks" type="button" onclick="opentable(event, 'move_user_and_assign_ot1')" id="defaultOpen_1">โยกย้ายแผนก/มอบหมาย OT</button>
        <button class="tablinks" type="button" onclick="opentable(event, 'update_ot1')">ตรวจสอบ OT</button>
        <!--<button class="tablinks" type="button" onclick="opentable(event, '#')">ปุ่มว่างให้เช่า ถ้าเพิ่มก็ไปแก้ใน css ด้วย</button> -->
    </div>

    <div id="move_user_and_assign_ot1" data-controller="checkbox" class="minitabcontent">
        <%=form_tag do%>
            <div class="form-check">
                <button type="button" data-action="checkbox#checkAll">เลือกทั้งหมด</button>
                <button type="button" data-action="checkbox#checkNone">ไม่เลือก</button>
                <%all_time = []%>
                <% for hour in (0..4)%>
                    <%for min in (0..1)%>
                        <% all_time.push((hour.to_s+":"+(min*30).to_s))%>
                    <%end%>
                <%end%>
                <%all_department = ['งานถอนขน','งานไก่ตกราว','งานเชือดไก่','งานสินค้าแช่แข็ง']%>

                <!--เทสปุ่ม เอาไว้เลือกแผนกที่จะย้ายให้ทั้งตาราง (บัคอยู่ ทำไม่เปลลลลลล)-->
                <%=select_tag :department,options_for_select(all_department),class:"department",include_blank:"เลือกแผนก",data:{action:"checkbox#setDepartment"} %>
                <%=select_tag :ot_time,options_for_select(all_time),class:"ot",data:{action:"checkbox#setOvertime"}%>
            </div>
            <table id="work1" class="table table-striped table-light" border="1" width="50%" cellspacing='0' cellpadding='10'>
                <thead>
                    <th>ชื่อ-นามสกุล</th>
                    <th>แผนก</th>
                    <th>OT time</th>
                    <th>OT check</th>
                </thead>
                <%#all_time.each{|time|[].push([time,row.user_id])}%>
                <tbody id="time_object">
                    <% @actual_time.each do |row|%>
                        <tr class=<%= User.find(row.user_id).name%>>
                            <% unless User.where(id:row.user_id,role:'คนงานทั่วไป',department: "งานถอนขน").length == 0%>
                                <td><%= User.find(row.user_id).name%></td>
                                <%@all_department_with_id=[]%>
                                <%all_department.map {|department| @all_department_with_id << [department,[department,row.user_id]]}%>
                                <td><%=select_tag "department_select[]",options_for_select(@all_department_with_id),include_blank:"เลือกแผนก",class:"department",data:{action:'click->checkbox#show_select_tag'}%></td>
                                <%@all_time_with_id=[]%>
                                <%all_time.map {|time| @all_time_with_id << [time,[time,row.user_id]]}%>
                                <td><%=select_tag "ot_time_select[]",options_for_select(@all_time_with_id),disabled:true,class:"ot",id:"select_"+row.user_id.to_s%></td>
                                <td><%=check_box_tag "chk",row.user_id,false,id:User.find(row.user_id).name,data:{action:'change->checkbox#setStatusSelectTag',target:'checkbox.overtime'}%></td>
                            <%end%>      
                        </tr>
                    <%end%>                       
                </tbody>
            </table>
            <%#<%=link_to "ยกเลิก",main_page_path,class:"btn btn-danger"%>
            <%#<%=submit_tag("ยืนยัน",class:"btn btn-success")%>
        <%end%>
    </div>

    <div id="update_ot1" data-controller="checkbox" class="minitabcontent">
        <%=form_tag method: :get do%>
            <!--<div id="ot_w1" >-->
            <div class="form-check">
                <button type="button" data-action="checkbox#checkAll">เลือกทั้งหมด</button>
                <button type="button" data-action="checkbox#checkNone">ไม่เลือก</button>
                <%all_time = []%>
                <% for hour in (0..4)%>
                    <%for min in (0..1)%>
                        <% all_time.push((hour.to_s+":"+(min*30).to_s))%>
                    <%end%>
                <%end%>
                <%=select_tag :ot_time,options_for_select(all_time),class:"ot",data:{action:"checkbox#setOvertime"}%>
            </div>
            <table id="work1" class="table table-striped table-light" border="1" width="50%" cellspacing='0' cellpadding='10'>
                <thead>
                    <th>ชื่อ-นามสกุล</th>
                    <th>OT time</th>
                    <th>OT check</th>
                </thead>
                <%#all_time.each{|time|[].push([time,row.user_id])}%>
                <tbody id="time_object">
                    <% @actual_time.each do |row|%>
                        <tr class=<%= User.find(row.user_id).name%>>
                            <% unless User.where(id:row.user_id,role:'คนงานทั่วไป',department: "งานถอนขน").length == 0%>
                                <td><%= User.find(row.user_id).name%></td>
                                <%@all_time_with_id=[]%>
                                <%all_time.map {|time| @all_time_with_id << [time,[time,row.user_id]]}%>
                                <td><%=select_tag "ot_time_select[]",options_for_select(@all_time_with_id),disabled:true,class:"ot",id:"select_"+row.user_id.to_s%></td>
                                <td><%=check_box_tag "chk[]",row.user_id,false,id:User.find(row.user_id).name,data:{action:'change->checkbox#setStatusSelectTag',target:'checkbox.overtime'}%></td>
                            <%end%>      
                        </tr>
                    <%end%>                       
                </tbody>
            </table>
            <%#<%=link_to "ยกเลิก",main_page_path,class:"btn btn-danger"%>
            <%#<%=submit_tag("อัปเดต",class:"btn btn-success")%>
        <%end%>
    </div>

    <script>
        function opentable(evt, tablename) {
            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("minitabcontent");
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablinks");
            for (i = 0; i < tablinks.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" active", "");
            }
            document.getElementById(tablename).style.display = "block";
            evt.currentTarget.className += " active";
        }
        // Get the element with id="defaultOpen" and click on it
        document.getElementById("defaultOpen_1").click();
        document.getElementsByClassName('tablinks')[0].click()
    </script>
</body>
</html>

CPF_work_schedule-master/app/views/manage_user/_manage_plan_w2_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="app/assets/stylesheet/style.css.scss" rel="stylesheet">
    <!-- font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@100;300&display=swap" rel="stylesheet">
    <!--<script type="text/javascript">  
            function selects(){  
                var ele=document.getElementsByName('chk');  
                for(var i=0; i<ele.length; i++){  
                    if(ele[i].type=='checkbox')  
                        ele[i].checked=true;  
                }  
            }  
            function deSelect(){  
                var ele=document.getElementsByName('chk');  
                for(var i=0; i<ele.length; i++){  
                    if(ele[i].type=='checkbox')  
                        ele[i].checked=false;  
                      
                }  
            }             
        </script>-->
</head>

<body>
    <div class="tab">
        <button class="tablinks" type="button" onclick="opentable(event, 'move_user_and_assign_ot2')" id="defaultOpen_2">โยกย้ายแผนก/มอบหมาย OT</button>
        <button class="tablinks" type="button" onclick="opentable(event, 'update_ot2')">ตรวจสอบ OT</button>
        <!--<button class="tablinks" type="button" onclick="opentable(event, '#')">ปุ่มว่างให้เช่า ถ้าเพิ่มก็ไปแก้ใน css ด้วย</button> -->
    </div>
    <div id="move_user_and_assign_ot2" data-controller="checkbox" class="minitabcontent">
        <%=form_tag do%>
            <div class="form-check">
                <button type="button" data-action="checkbox#checkAll">เลือกทั้งหมด</button>
                <button type="button" data-action="checkbox#checkNone">ไม่เลือก</button>
                <%all_time = []%>
                <% for hour in (0..4)%>
                    <%for min in (0..1)%>
                        <% all_time.push((hour.to_s+":"+(min*30).to_s))%>
                    <%end%>
                <%end%>
                <%all_department = ['งานถอนขน','งานไก่ตกราว','งานเชือดไก่','งานสินค้าแช่แข็ง']%>
                <%=select_tag :department,options_for_select(all_department),class:"department",include_blank:"เลือกแผนก",data:{action:"checkbox#setDepartment"} %>
                <%=select_tag :ot_time,options_for_select(all_time),class:"ot",data:{action:"checkbox#setOvertime"}%>
            </div>

            <table id="work2" class="table table-striped table-light" border="1" width="50%" cellspacing='0' cellpadding='10'>
                <thead>
                    <th>ชื่อ-นามสกุล</th>
                    <th>แผนก</th>
                    <th>OT time</th>
                    <th>OT check</th>
                </thead>
                <%#all_time.each{|time|[].push([time,row.user_id])}%>
                <tbody id="time_object">
                    <% @actual_time.each do |row|%>
                        <tr class=<%= User.find(row.user_id).name%>>
                            <% unless User.where(id:row.user_id,role:'คนงานทั่วไป',department: "งานไก่ตกราว").length == 0%>
                                <td><%= User.find(row.user_id).name%></td>
                                <%@all_department_with_id=[]%>
                                <%all_department.map {|department| @all_department_with_id << [department,[department,row.user_id]]}%>
                                <td><%=select_tag "department_select[]",options_for_select(@all_department_with_id),include_blank:"เลือกแผนก",class:"department"%></td>
                                <%@all_time_with_id=[]%>
                                <%all_time.map {|time| @all_time_with_id << [time,[time,row.user_id]]}%>
                                <td><%=select_tag "ot_time_select[]",options_for_select(@all_time_with_id),disabled:true,class:"ot",id:"select_"+row.user_id.to_s%></td>
                                <td><%=check_box_tag "chk[]",row.user_id,false,id:User.find(row.user_id).name,data:{action:'change->checkbox#setStatusSelectTag',target:'checkbox.overtime'}%></td>
                            <%end%>      
                        </tr>
                    <%end%>                       
                </tbody>
            </table>

            <%#<%=link_to "ยกเลิก",main_page_path,class:"btn btn-danger"%>
            <%#<%=submit_tag("ยืนยัน",class:"btn btn-success")%>
        <%end%>
    </div>
    <div id="update_ot2" data-controller="checkbox" class="minitabcontent">
        <%=form_tag method: :get do%>
            <!--<div id="ot_w1" >-->
            <div class="form-check">
                <button type="button" data-action="checkbox#checkAll">เลือกทั้งหมด</button>
                <button type="button" data-action="checkbox#checkNone">ไม่เลือก</button>
                <%all_time = []%>
                <% for hour in (0..4)%>
                    <%for min in (0..1)%>
                        <% all_time.push((hour.to_s+":"+(min*30).to_s))%>
                    <%end%>
                <%end%>
                <%=select_tag :ot_time,options_for_select(all_time),class:"ot",data:{action:"checkbox#setOvertime"}%>
            </div>
            <table id="work2" class="table table-striped table-light" border="1" width="50%" cellspacing='0' cellpadding='10'>
                <thead>
                    <th>ชื่อ-นามสกุล</th>
                    <th>OT time</th>
                    <th>OT check</th>
                </thead>
                <%#all_time.each{|time|[].push([time,row.user_id])}%>
                <tbody id="time_object">
                    <% @actual_time.each do |row|%>
                        <tr class=<%= User.find(row.user_id).name%>>
                            <% unless User.where(id:row.user_id,role:'คนงานทั่วไป',department: "งานไก่ตกราว").length == 0%>
                                <td><%= User.find(row.user_id).name%></td>
                                <%@all_time_with_id=[]%>
                                <%all_time.map {|time| @all_time_with_id << [time,[time,row.user_id]]}%>
                                <td><%=select_tag "ot_time_select[]",options_for_select(@all_time_with_id),disabled:true,class:"ot",id:"select_"+row.user_id.to_s%></td>
                                <td><%=check_box_tag "chk[]",row.user_id,false,id:User.find(row.user_id).name,data:{action:'change->checkbox#setStatusSelectTag',target:'checkbox.overtime'}%></td>
                            <%end%>      
                        </tr>
                    <%end%>                       
                </tbody>
            </table>
            <%#<%=link_to "ยกเลิก",main_page_path,class:"btn btn-danger"%>
            <%#<%=submit_tag("อัปเดต",class:"btn btn-success")%>
        <%end%>
    </div>

    <script>
        function opentable(evt, tablename) {
            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("minitabcontent");
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablinks");
            for (i = 0; i < tablinks.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" active", "");
            }
            document.getElementById(tablename).style.display = "block";
            evt.currentTarget.className += " active";
        }
        // Get the element with id="defaultOpen" and click on it
        document.getElementById("defaultOpen_2").click();
        document.getElementsByClassName('tablinks')[0].click()
    </script>

</body>
</html>

CPF_work_schedule-master/app/views/manage_user/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- font -->  
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@100;200&display=swap" rel="stylesheet">
    <title> index </title>

    <script type="text/javascript"> 
        function display_c(){
            var refresh=1000; // Refresh rate in milli seconds
            mytime=setTimeout('display_ct()',refresh)
        }

        function display_ct() {
            var x = new Date()
            var x1="วันที่ : "+ x.getDate() + "/"+ (parseInt(x.getMonth(), 10)+1)   + "/" + x.getFullYear(); 
            x1 = x1 + " เวลา : " +  x.getHours( )+ ":" +  x.getMinutes() + ":" +  x.getSeconds();
            document.getElementById('ct').innerHTML = x1;
            display_c();
        }

    </script>
</head>
<body onload=display_ct();>
    <header>
        <div class="d-flex flex-row-reverse align-items-center">
    
            <%=link_to logout_path do%>
                <i class="bi bi-box-arrow-right btn btn-danger display-font" id="logout-button" aria-hidden="true"> Logout </i>
            <%end%>
                
            <div class='flex-grow-1 text-center display-3 display-font text-light' id="header-text" text-align="center">CPF schedule workplan</div>

                <i class="bi bi-file-person btn btn-primary display-font" id="logout-button" aria-hidden="true"> <%=@current_user.role%> </i>
        </div>
    </header>

    <div class="d-flex flex-row align-items-center">
        <div class="d-flex flex-column flex-grow-1">
            <p></p>
            <div class="display-font"> ชื่อ-นามสกุล : <%=@current_user.name %> </div>
            <div class="display-font"> สถานที่ทำงาน : <%= @current_user.factory %></div>
            <div class="display-font"> ตำแหน่ง : <%= @current_user.role %> </div>
            <p></p>
        </div>

        <div class="flex-grow-1 align-items-center">
            <h3 id='ct' class="display-font"></h3>
        </div>

        <span class="flex-grow-1 align-items-center">
            <% if @actual_time.where(user_id: @current_user.id).length == 0%>
                <%= link_to timestamp_path(@current_user) do%>
                    <i class="bi bi-chevron-double-right btn btn-primary" id="logout-button" aria-hidden="true"> Check-IN </i>
            <%end%>
            <% else %>
                <%= link_to timestamp_path(@current_user) do%>
                    <i class="bi bi-chevron-double-right btn btn-red" id="logout-button" aria-hidden="true"> Check-OUT </i>
                <% end %>
            <% end %>

        </span>
    </div>
    <div id="myHeader">
        <button class="tablink" onclick="openPage('work1', this, '#5BA8A0')" id="defaultOpen">ถอนขน</button>
        <button class="tablink" onclick="openPage('work2', this, '#CBE54E')">ไก่ตกราว</button>
        <button class="tablink" onclick="openPage('work3', this, '#94B447')">เชือดไก่</button>
        <button class="tablink" onclick="openPage('work4', this, '#5D6E1E')">สินค้าแช่แข็ง</button>
    </div>
    <div>
        <div id="work1" class="tabcontent">
            <div class="display-font h3 text-center">
                จำนวนพนักงาน : <%=User.where(role:'คนงานทั่วไป',factory:@current_user.factory,department:"งานถอนขน").length%> / 10 
                <!-- จำนวนพนักงาน : <%=@actual_time.length%> / 10 -->
                <%=render "manage_plan_w1_form"%>
                <%=link_to "ยกเลิก",main_page_path,class:"btn btn-danger"%>
                <%=submit_tag("อัปเดต",class:"btn btn-success")%>
            </div>
        </div>
        <div id="work2" class="tabcontent">
             <div class="display-font h3 text-center">
                จำนวนพนักงาน : <%=User.where(role:'คนงานทั่วไป',factory:@current_user.factory,department:"งานไก่ตกราว").length%> / 10 
                <!-- จำนวนพนักงาน : <%=@actual_time.length%> / 10 -->
                <%=render "manage_plan_w2_form"%>
                <%=link_to "ยกเลิก",main_page_path,class:"btn btn-danger"%>
                <%=submit_tag("อัปเดต",class:"btn btn-success")%>
            </div>
        </div>
        <div id="work3" class="tabcontent">
             <div class="display-font h3 text-center">
                จำนวนพนักงาน : <%=User.where(role:'คนงานทั่วไป',factory:@current_user.factory,department:"งานเชือดไก่").length%> / 10 
                <!-- จำนวนพนักงาน : <%=@actual_time.length%> / 10 -->
                <%=render "manage_plan_w3_form"%>
                <%=link_to "ยกเลิก",main_page_path,class:"btn btn-danger"%>
                <%=submit_tag("อัปเดต",class:"btn btn-success")%>
            </div>
        </div>

        <div id="work4" class="tabcontent">
             <div class="display-font h3 text-center">
                จำนวนพนักงาน : <%=User.where(role:'คนงานทั่วไป',factory:@current_user.factory,department:"งานสินค้าแช่แข็ง").length%> / 10 
                <!-- จำนวนพนักงาน : <%=@actual_time.length%> / 10 -->
                <%=render "manage_plan_w4_form"%>
                <%=link_to "ยกเลิก",main_page_path,class:"btn btn-danger"%>
                <%=submit_tag("อัปเดต",class:"btn btn-success")%>
            </div>
        </div>
    </div> 
    <script>
        //full page tab
        function openPage(pageName,elmnt,color) {
        var i, tabcontent, tablinks,department;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablink");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].style.backgroundColor = "";
        }
        document.getElementById(pageName).style.display = "block";
        elmnt.style.backgroundColor = color;
        }
        document.getElementById("defaultOpen").click();

        window.onscroll = function() {myFunction()};
        
        //fixed tab
        var header = document.getElementById("myHeader");
        var sticky = header.offsetTop;
        function myFunction() {
            if (window.pageYOffset > sticky) {
            header.classList.add("sticky");
            } else {
            header.classList.remove("sticky");
            }
        }
    </script>

</body>
</html>