CPF_work_schedule-cpf_branch_3/config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/login')
  resources :users do
    resources :schedule_actual_times
  end
  get '/main_page', to: 'dashboard#index'
  get '/login', to: 'login#login_new'
  post '/login',to: 'login#create'
  get '/register', to: 'login#register_new'
  post '/register',to: 'login#register'
  get '/register_user', to: 'dashboard#register_user'
  post '/register_user',to: 'dashboard#register'
  get '/logout',to: 'dashboard#destroy'
  get '/timestamp/:id',to: 'dashboard#check_timestamp',as: 'timestamp'
  get '/manage_user',to: 'manage_user#index'
  post '/manage_user',to: 'manage_user#set_plan'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

CPF_work_schedule-cpf_branch_3/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
        @current_user = current_user
        @actual_time = ScheduleActualTime.all
        @history = History.all
        @shift_code = Shiftcode.all
    end
    def register_new;
        user = User.new;
        @plan_time = SchedulePlantime.new
        @shift_code = Shiftcode.all
    end
    def destroy
        log_out
        redirect_to root_path
    end

    def check_timestamp
        @lat_lng = cookies[:lat_lng]
        if ScheduleActualTime.all.where(user_id: current_user.id).length == 0
            @time_object = ScheduleActualTime.create(
                :time_in=>DateTime.now()
            )
            current_user.schedule_actual_times << @time_object
            @time_object1 = History.create(
                :user_id => current_user.id,
                :time_in=>DateTime.now()
            )
            current_user.histories << @time_object1
            ActionCable.server.broadcast(
                'actual_time_channel',{
                name: current_user.name,
                time_in: @time_object.time_in.strftime("%H:%M:%S"),
                time_out:"-",
                department: current_user.department,
                role: current_user.role,
                act: "show"
                }
            )
        else 
            @time_object = ScheduleActualTime.find_by(user_id: current_user.id).update(
                :time_out=>DateTime.now()
            )
            @time_object1 = History.find_by(user_id: current_user.id).update(
                :time_out=>DateTime.now()
            )

            ActionCable.server.broadcast(
                'actual_time_channel',{
                name: current_user.name,
                time_in: ScheduleActualTime.find_by(user_id: current_user.id).time_in.strftime("%H:%M:%S"),
                time_out: ScheduleActualTime.find_by(user_id: current_user.id).time_out.strftime("%H:%M:%S"),
                department: current_user.department,
                role: current_user.role,
                act: "delete"
                }
            )
        end 
        redirect_to main_page_path
    end

    def register
        @random_number = rand(1000..9999) 
        @user_find = User.find_by(name: params[:name])
        if @user_find.nil? #ถ้าไม่เจอชื่อซ้ำใน database
            user = User.create!(:employee_id=>@random_number,
                :title_name=>params[:title_name],
                :name=>params[:name],
                :password=>params[:password],
                :factory=>params[:factory],
                :department=>params[:department],
                :hire_date=>DateTime.now,
                :employee_income_type=>params[:employee_income_type],
                :role=>params[:role])
            user.shiftcodes << Shiftcode.find_by(code_name:params[:shift_code_select])
            redirect_to main_page_path
        else
          render 'register_user'
        end
        
    end 
end

CPF_work_schedule-cpf_branch_3/app/controllers/manage_user_controller.rb
class ManageUserController < ApplicationController
    def index
        @current_user = current_user
        @actual_time = ScheduleActualTime.all
    end
    def set_plan
        @plan_all = params
        puts @plan_all
    end
end

CPF_work_schedule-cpf_branch_3/app/views/dashboard/_cheif.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="app/assets/stylesheet/style.css.scss" rel="stylesheet">
    <title> cheif </title>

    <script type="text/javascript"> 
        function display_c(){
            var refresh=1000; // Refresh rate in milli seconds
            mytime=setTimeout('display_ct()',refresh)
        }

        function display_ct() {
            var x = new Date()
            var x1="วันที่ : "+ x.getDate() + "/"+ (parseInt(x.getMonth(), 10)+1)   + "/" + x.getFullYear(); 
            x1 = x1 + " เวลา : " +  x.getHours( )+ ":" +  x.getMinutes() + ":" +  x.getSeconds();
            document.getElementById('ct').innerHTML = x1;
            display_c();
        }

    </script>
</head>

<!---------------------------------------------------โปรไฟล์---------------------------------------------------------- -->

<body onload=display_ct();>
    <div class="d-flex flex-row align-items-center">
        <div class="d-flex flex-column flex-grow-1">
            <div class="display-font"> ชื่อ-นามสกุล : <%=@current_user.name %> </div>
            <div class="display-font"> สถานที่ทำงาน : <%= @current_user.factory %></div>
            <div class="display-font"> ตำแหน่ง : <%= @current_user.role %> </div>
        </div>

        <div class="flex-grow-1 align-items-center">
            <h3 id='ct' class="display-font"></h3>

        </div>

        <span class="flex-grow-1 align-items-center">
            <% if @actual_time.where(user_id: @current_user.id).length == 0%>
                <%= link_to timestamp_path(@current_user) do%>
                    <i class="bi bi-chevron-double-right btn btn-primary" id="logout-button" aria-hidden="true"> Check-IN </i>
            <%end%>
            <% else %>
                <%= link_to timestamp_path(@current_user) do%>
                    <i class="bi bi-chevron-double-right btn btn-red" id="logout-button" aria-hidden="true"> Check-OUT </i>
                <% end %>
            <% end %>

        </span>
    </div>
    
<!-- -------------------------------------------------ตารางคนเข้างาน---------------------------------------------------------- -->
    <div id="myHeader">
        <button class="tablink" onclick="openPage('work1', this, '#5BA8A0')" id="defaultOpen">ถอนขน</button>
        <button class="tablink" onclick="openPage('work2', this, '#CBE54E')">ไก่ตกราว</button>
        <button class="tablink" onclick="openPage('work3', this, '#94B447')">เชือดไก่</button>
        <button class="tablink" onclick="openPage('work4', this, '#5D6E1E')">สินค้าแช่แข็ง</button>
    </div>
    <div id="work1" class="tabcontent">
            <div class="display-font h3 text-center">
                จำนวนพนักงาน(ที่มี/ต้องการ) <%=User.where(role:'คนงานทั่วไป',factory:@current_user.factory,department:"งานถอนขน").length%> / 20 
            </div>
            <%# <% @actual_time.each do |row|%> 
                <%# <% unless User.where(id:row.user_id,role:'คนงานทั่วไป',factory:@current_user.factory,department:"งานถอนขน").length == 0%> 
                <%# <div> %>
                    <%# <%= User.find(row.user_id).name%> 
                    <%# <%= row.time_in%> 
                <%# </div> %>
                <%# <%end%> 
            <%# <%end%>   
            <%# ======================================================================================================================= %>
            <table class="table table-striped table-light" border="1" width="50%" cellspacing='0' cellpadding='10'>
                <thead>
                    <th>ชื่อ-นามสกุล</th>
                    <th>เวลา-เข้า</th>
                    <th>เวลา-ออก</th>
                    <th>ช่วงเวลาทำงาน</th>
                    <th>โรงงาน</th>
                    <th>OT</th>
                </thead>
                <tbody id="งานถอนขน_c">
                    <% @actual_time.each do |row|%>
                        <tr id=<%= User.find(row.user_id).name%>>
                            <% unless User.where(id:row.user_id,role:'คนงานทั่วไป',department: "งานถอนขน",factory:@current_user.factory).length == 0%>
                                <td><%= User.find(row.user_id).name%></td>
                                <td><%= row.time_in.strftime("%H:%M:%S")%></td>
                                <% if row.time_out.nil?%>
                                    <td>#</td>
                                <% else %>
                                    <td><%= row.time_out.strftime("%H:%M:%S")%></td>
                                <% end %>
                                <td><%=  %></td>
                                <td><%= User.find(row.user_id).factory%></td>
                                <td><%=  %></td>
                            <%end%>
                        </tr>
                    <%end%>                       
                </tbody>
            </table>
            <div class="text-center"> <!-- d-flex align-items-center justify-content-center -->
                <%= link_to register_user_path do %><i class="bi bi-plus btn btn-primary col-6 mx-auto">Add person</i><%end%>
            </div> 
        </div>

        <div id="work2" class="tabcontent">
            <div class="display-font h3 text-center">
                จำนวนพนักงาน(ที่มี/ต้องการ) <%=User.where(role:'คนงานทั่วไป',factory:@current_user.factory,department:"งานไก่ตกราว").length%> / 20
            </div>
             <!-- <% @actual_time.each do |row|%>
                <% unless User.where(id:row.user_id,role:'คนงานทั่วไป',factory:@current_user.factory,department:"งานไก่ตกราว").length == 0%>
                    <div>
                        <%= User.find(row.user_id).name%>
                        <%= row.time_in%>
                    </div>
                <%end%>
            <%end%> -->
            <table class="table table-striped table-light" border="1" width="50%" cellspacing='0' cellpadding='10'>
                <thead>
                    <th>ชื่อ-นามสกุล</th>
                    <th>เวลา-เข้า</th>
                    <th>เวลา-ออก</th>
                    <th>ช่วงเวลาทำงาน</th>
                    <th>โรงงาน</th>
                    <th>OT</th>
                </thead>
                <tbody id="งานไก่ตกราว_c">
                    <% @actual_time.each do |row|%>
                        <tr id=<%= User.find(row.user_id).name%>>
                            <% unless User.where(id:row.user_id,role:'คนงานทั่วไป',department:"งานไก่ตกราว",factory:@current_user.factory).length == 0%>
                                <td><%= User.find(row.user_id).name%></td>
                                <td ><%= row.time_in.strftime("%H:%M:%S")%></td>
                                <% if row.time_out.nil?%>
                                    <td>#</td>
                                <% else %>
                                    <td><%= row.time_out.strftime("%H:%M:%S")%></td>
                                <% end %>
                                <td>...</td>
                                <td><%= User.find(row.user_id).factory%></td>
                                <td>...</td>
                            <%end%>
                        </tr>
                    <%end%>                       
                </tbody>
            </table>
            <div class="text-center"> <!-- d-flex align-items-center justify-content-center -->
                <%= link_to register_user_path do %><i class="bi bi-plus btn btn-primary col-6 mx-auto">Add person</i><%end%>
            </div> 
        </div>

        <div id="work3" class="tabcontent">
            <div class="display-font h3 text-center">
                จำนวนพนักงาน(ที่มี/ต้องการ) <%=User.where(role:'คนงานทั่วไป',factory:@current_user.factory,department:"งานเชือดไก่").length%> / 20
            </div>
            <!-- <% @actual_time.each do |row|%>
                <% unless User.where(id:row.user_id,role:'คนงานทั่วไป',factory:@current_user.factory,department:"งานเชือดไก่").length == 0%>
                    <div>
                        <%= User.find(row.user_id).name%>
                        <%= row.time_in%>
                    </div>
                <%end%>
            <%end%> -->
            <table class="table table-striped table-light" border="1" width="50%" cellspacing='0' cellpadding='10'>
                <thead>
                    <th>ชื่อ-นามสกุล</th>
                    <th>เวลา-เข้า</th>
                    <th>เวลา-ออก</th>
                    <th>ช่วงเวลาทำงาน</th>
                    <th>โรงงาน</th>
                    <th>OT</th>
                </thead>
                <tbody id="งานเชือดไก่_c">
                    <% @actual_time.each do |row|%>
                        <tr id=<%= User.find(row.user_id).name%>>
                            <% unless User.where(id:row.user_id,role:'คนงานทั่วไป',department:"งานเชือดไก่",factory:@current_user.factory).length == 0%>
                                <td><%= User.find(row.user_id).name%></td>
                                <td ><%= row.time_in.strftime("%H:%M:%S")%></td>
                                <% if row.time_out.nil?%>
                                    <td>#</td>
                                <% else %>
                                    <td><%= row.time_out.strftime("%H:%M:%S")%></td>
                                <% end %>
                                <td>...</td>
                                <td><%= User.find(row.user_id).factory%></td>
                                <td>...</td>
                            <%end%>
                        </tr>
                    <%end%>                       
                </tbody>
            </table>
            <div class="text-center"> <!-- d-flex align-items-center justify-content-center -->
                <%= link_to register_user_path do %><i class="bi bi-plus btn btn-primary col-6 mx-auto">Add person</i><%end%>
            </div> 
        </div>

        <div id="work4" class="tabcontent">
            <div class="display-font h3 text-center">
                จำนวนพนักงาน(ที่มี/ต้องการ) <%=User.where(role:'คนงานทั่วไป',factory:@current_user.factory,department:"งานจัดเก็บและจ่ายสินค้าแช่แข็ง").length%> / 20 
            </div>
            <!-- <% @actual_time.each do |row|%>
                <% unless User.where(id:row.user_id,role:'คนงานทั่วไป',factory:@current_user.factory,department:"สินค้าแช่แข็ง").length == 0%>
                    <div>
                        <%= User.find(row.user_id).name%>
                        <%= row.time_in%>
                    </div>
                <%end%>
            <%end%> -->
            <table class="table table-striped table-light" border="1" width="50%" cellspacing='0' cellpadding='10'>
                <thead>
                    <th>ชื่อ-นามสกุล</th>
                    <th>เวลา-เข้า</th>
                    <th>เวลา-ออก</th>
                    <th>ช่วงเวลาทำงาน</th>
                    <th>โรงงาน</th>
                    <th>OT</th>
                </thead>
                <tbody id="งานจัดเก็บและจ่ายสินค้าแช่แข็ง_c">
                    <% @actual_time.each do |row|%>
                        <tr id=<%= User.find(row.user_id).name%> >
                            <% unless User.where(id:row.user_id,role:'คนงานทั่วไป',department: "งานจัดเก็บและจ่ายสินค้าแช่แข็ง").length == 0%>
                                <td><%= User.find(row.user_id).name%></td>
                                <td ><%= row.time_in.strftime("%H:%M:%S")%></td>
                                <% if row.time_out.nil?%>
                                    <td>#</td>
                                <% else %>
                                    <td><%= row.time_out.strftime("%H:%M:%S")%></td>
                                <% end %>
                                <td>...</td>
                                <td><%= User.find(row.user_id).factory%></td>
                                <td>...</td>
                            <%end%>
                        </tr>
                    <%end%>                       
                </tbody>
            </table>
            <div class="text-center"> <!-- d-flex align-items-center justify-content-center -->
                <%= link_to register_user_path do %><i class="bi bi-plus btn btn-primary col-6 mx-auto">Add person</i><%end%>
            </div> 
    </div>

    <!-- full page tab script -->
    <script> 
        //full page tab
        function openPage(pageName,elmnt,color) {
        var i, tabcontent, tablinks,department;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablink");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].style.backgroundColor = "";
        }
        document.getElementById(pageName).style.display = "block";
        elmnt.style.backgroundColor = color;
        }
        document.getElementById("defaultOpen").click();

        window.onscroll = function() {myFunction()};
        
        //fixed tab
        var header = document.getElementById("myHeader");
        var sticky = header.offsetTop;
        function myFunction() {
            if (window.pageYOffset > sticky) {
            header.classList.add("sticky");
            } else {
            header.classList.remove("sticky");
            }
        }
    </script>
    <div class="text-center d-grid" style="position: fixed; bottom:0px; height:40px; left:0px; right:0px; overflow:hidden">
        <%=link_to "จัดการเวลาทำงาน",manage_user_path,class:"btn btn-info display-font"%>
    </div>
</body>
</html>

CPF_work_schedule-cpf_branch_3/app/views/dashboard/_worker.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="app/assets/stylesheet/style.css.scss" rel="stylesheet">
        <title> worker </title>

        <script type="text/javascript"> 
            function display_c(){
                var refresh=1000; // Refresh rate in milli seconds
                mytime=setTimeout('display_ct()',refresh)
            }

            function display_ct() {
                var x = new Date()
                var x1="วันที่ : "+ x.getDate() + "/"+ (parseInt(x.getMonth(), 10)+1)   + "/" + x.getFullYear(); 
                x1 = x1 + " เวลา : " +  x.getHours( )+ ":" +  x.getMinutes() + ":" +  x.getSeconds();
                document.getElementById('ct').innerHTML = x1;
                display_c();
            }
        </script>
    </head>

<!---------------------------------------------------โปรไฟล์---------------------------------------------------------- -->
    <body onload=display_ct();>

    <div class="d-flex flex-row align-items-center">
        <div class="d-flex flex-column flex-grow-1">
            <div class="display-font"> ชื่อ-นามสกุล : <%=@current_user.name %> </div>
            <div class="display-font"> สถานที่ทำงาน : <%= @current_user.factory %></div>
            <div class="display-font"> แผนก : <%= @current_user.department %> </div>
        </div>

        <div class="flex-grow-1 align-items-center">
            <h3 id='ct' class="display-font"></h3>
        </div>

        <div class="flex-grow-1 align-items-center">
            <% if @actual_time.where(user_id: @current_user.id).length == 0 %>
                <%= link_to timestamp_path(@current_user) do%>
                    <i class="bi bi-chevron-double-right btn btn-success" id="logout-button" aria-hidden="true"> Check-IN </i>
            <%end%>
            <% else %>
                <%= link_to timestamp_path(@current_user) do%>
                    <i class="bi bi-chevron-double-right btn btn-red" id="logout-button" aria-hidden="true"> Check-OUT </i>
                <% end %>
            <% end %>
        </div>
    </div>

<!-- -------------------------------------------------สถิติการทำงาน---------------------------------------------------------- -->

    <div class="d-flex flex-row align-items-center">
        <div class="d-flex flex-column flex-grow-1">
            <div class="display-font"> จำนวนชั่วโมงทั้งหมด : ... </div>
            <div class="display-font"> จำนวนชั่วโมง OT ทั้งหมด : ...</div>
        </div>
    </div>

<!-- -------------------------------------------------ตารางคนเข้างาน---------------------------------------------------------- -->
           
    <h3 class="display-font text-center"> ตารางบันทึกการทำงาน </h3>
    <div class="content display-font">
        <table class="table table-striped table-light display-font text-center" border="1" width="50%" cellspacing='0' cellpadding='10'>
            <thead>
                <th>วันที่</th>
                <th>เวลา-เข้า</th>
                <th>เวลา-ออก</th>
                <th>ช่วงเวลาทำงาน</th>
                <th>จำนวน OT</th>
            </thead>

            <tbody id="worker_time">
                <% for i in (1..30) %>
                    <tr>                                      
                        <td>
                            <%= i %>
                        </td>
                        <% unless @history.find_by(user_id: @current_user.id).nil?%>
                            <% if i.to_s == @history.find_by(user_id: @current_user.id).time_in.strftime('%d')%>
                                <td>
                                    <%= @history.find_by(user_id: @current_user.id).time_in.strftime("%H:%M:%S")%>
                                </td>
                                <td>
                                    <% unless @history.find_by(user_id: @current_user.id).time_out.nil?%>
                                        <%= @history.find_by(user_id: @current_user.id).time_out.strftime("%H:%M:%S")%>
                                    <% end %>
                                </td>
                                <td>
                                    ...
                                </td>                                
                            <% elsif i < @history.find_by(user_id: @current_user.id).time_in.strftime('%d').to_i %>
                                <% for j in (1..4) %>
                                    <td>
                                        -
                                    </td>
                                <% end %>
                            <% end %>
                        <% end %>
                    </tr>    
                <% end %>                  
            </tbody>
        </table>
    </div>
            
    </body>
</html>  

CPF_work_schedule-cpf_branch_3/app/views/dashboard/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> index </title>
    </head>
    <body>
        <header>
            <div class="d-flex flex-row-reverse align-items-center">
    
                <%=link_to logout_path do%>
                    <i class="bi bi-box-arrow-right btn btn-danger display-font" id="logout-button" aria-hidden="true"> Logout </i>
                <%end%>
                
                <div class='flex-grow-1 text-center display-3 display-font text-light' id="header-text" text-align="center">CPF schedule workplan</div>
            </div>
        </header>

        <% if @current_user.role =="ผู้จัดการ"%>
            <%= render "manager" %>
        <% elsif @current_user.role =="หัวหน้าแผนก"%>
            <%= render "cheif" %>
        <% elsif @current_user.role =="คนงานทั่วไป"%>
            <%= render "worker" %>
        <% else%>
            <p>404 Not found <%@current_user.name%></p>
        <% end%>
        
    </body>
</html>

CPF_work_schedule-cpf_branch_3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CpfAttendence</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="<%= "controller_#{controller.controller_name}" %>">
    <%= yield %>
  </body>
</html>

CPF_work_schedule-cpf_branch_3/app/views/login/register_new.html.haml
= render :partial => 'user_form'

CPF_work_schedule-cpf_branch_3/app/views/manage_user/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> index </title>

    <script type="text/javascript"> 
        function display_c(){
            var refresh=1000; // Refresh rate in milli seconds
            mytime=setTimeout('display_ct()',refresh)
        }

        function display_ct() {
            var x = new Date()
            var x1="วันที่ : "+ x.getDate() + "/"+ (parseInt(x.getMonth(), 10)+1)   + "/" + x.getFullYear(); 
            x1 = x1 + " เวลา : " +  x.getHours( )+ ":" +  x.getMinutes() + ":" +  x.getSeconds();
            document.getElementById('ct').innerHTML = x1;
            display_c();
        }

    </script>
</head>
<body onload=display_ct();>
    <header>
        <div class="d-flex flex-row-reverse align-items-center">
    
            <%=link_to logout_path do%>
                <i class="bi bi-box-arrow-right btn btn-danger" id="logout-button" aria-hidden="true"> Logout </i>
            <%end%>
                
            <div class='flex-grow-1 text-center display-3 text-light' id="header-text" text-align="center">CPF schedule workplan</div>
        </div>
    </header>

    <div class="d-flex flex-row align-items-center">
        <div class="d-flex flex-column flex-grow-1">
            <div class="display-font"> ชื่อ-นามสกุล : <%=@current_user.name %> </div>
            <div class="display-font"> สถานที่ทำงาน : <%= @current_user.factory %></div>
            <div class="display-font"> ตำแหน่ง : <%= @current_user.role %> </div>
        </div>

        <div class="flex-grow-1 align-items-center">
            <h3 id='ct' class="display-font"></h3>
        </div>

        <span class="flex-grow-1 align-items-center">
            <% if @actual_time.where(user_id: @current_user.id).length == 0%>
                <%= link_to timestamp_path(@current_user) do%>
                    <i class="bi bi-chevron-double-right btn btn-primary" id="logout-button" aria-hidden="true"> Check-IN </i>
            <%end%>
            <% else %>
                <%= link_to timestamp_path(@current_user) do%>
                    <i class="bi bi-chevron-double-right btn btn-red" id="logout-button" aria-hidden="true"> Check-OUT </i>
                <% end %>
            <% end %>

        </span>
    </div>
    <div id="myHeader">
        <button class="tablink" onclick="openPage('work1', this, '#5BA8A0')" id="defaultOpen">ถอนขน</button>
        <button class="tablink" onclick="openPage('work2', this, '#CBE54E')">ไก่ตกราว</button>
        <button class="tablink" onclick="openPage('work3', this, '#94B447')">เชือดไก่</button>
        <button class="tablink" onclick="openPage('work4', this, '#5D6E1E')">สินค้าแช่แข็ง</button>
    </div>
    <div>
        <div id="work1" class="tabcontent">
            <div class="display-font h3 text-center">
                จำนวนพนักงาน : <%=User.where(role:'คนงานทั่วไป',factory:@current_user.factory,department:"งานถอนขน").length%> / 10
                <%=render "manage_plan_w1_form"%>
            </div>
        </div>
        <div id="work2" class="tabcontent">
             <div class="display-font h3 text-center">
                จำนวนพนักงาน : <%=User.where(role:'คนงานทั่วไป',factory:@current_user.factory,department:"งานไก่ตกราว").length%> / 10 
                <%=render "manage_plan_w2_form"%>
            </div>
        </div>
        <div id="work3" class="tabcontent">
             <div class="display-font h3 text-center">
                จำนวนพนักงาน : <%=User.where(role:'คนงานทั่วไป',factory:@current_user.factory,department:"งานเชือดไก่").length%> / 10 
                <%=render "manage_plan_w3_form"%>
            </div>
        </div>

        <div id="work4" class="tabcontent">
             <div class="display-font h3 text-center">
                จำนวนพนักงาน : <%=User.where(role:'คนงานทั่วไป',factory:@current_user.factory,department:"งานสินค้าแช่แข็ง").length%> / 10 
                <%=render "manage_plan_w4_form"%>
            </div>
        </div>
    </div> 
    <script>
        //full page tab
        function openPage(pageName,elmnt,color) {
        var i, tabcontent, tablinks,department;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablink");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].style.backgroundColor = "";
        }
        document.getElementById(pageName).style.display = "block";
        elmnt.style.backgroundColor = color;
        }
        document.getElementById("defaultOpen").click();

        window.onscroll = function() {myFunction()};
        
        //fixed tab
        var header = document.getElementById("myHeader");
        var sticky = header.offsetTop;
        function myFunction() {
            if (window.pageYOffset > sticky) {
            header.classList.add("sticky");
            } else {
            header.classList.remove("sticky");
            }
        }
    </script>

</body>
</html>